import { Song } from './types';

export const SONGS: Song[] = [
  // 1. Legend (Prince Royce, Romeo Santos, Aventura)
  { title: "Inmortal", artist: "Aventura", category: "legend", year: 2019 },
  { title: "Dile al Amor", artist: "Aventura", category: "legend", year: 2009 },
  { title: "Obsesión", artist: "Aventura", category: "legend", year: 2002 },
  { title: "Carita de Inocente", artist: "Prince Royce", category: "legend", year: 2020 },
  { title: "Te Espero", artist: "Prince Royce ft. Maria Becerra", category: "legend", year: 2022 },
  { title: "Deja Vu", artist: "Prince Royce & Shakira", category: "legend", year: 2017 },
  { title: "No Me Olvides", artist: "Prince Royce", category: "legend", year: 2022 },
  { title: "Borrador", artist: "Prince Royce", category: "legend", year: 2023 },
  { title: "Tu Feo", artist: "Prince Royce ft. Lenny Tavarez", category: "legend", year: 2023 },
  { title: "Go Your Own Way", artist: "Prince Royce ft. This City", category: "legend", year: 2022 },
  { title: "Propuesta Indecente", artist: "Romeo Santos", category: "legend", year: 2013 },
  { title: "Perjurio", artist: "Romeo Santos", category: "legend", year: 2017 },
  { title: "Boomerang", artist: "Romeo Santos", category: "legend", year: 2023 },
  { title: "Eres Mía", artist: "Romeo Santos", category: "legend", year: 2014 },

  // 2. Sensual (Pinto Picasso, Mayinbito, Montelier)
  { title: "Vanidad", artist: "Pinto Picasso", category: "sensual", year: 2020 },
  { title: "Que Pena", artist: "Pinto Picasso", category: "sensual", year: 2021 },
  { title: "Feeling Something", artist: "Pinto Picasso", category: "sensual", year: 2021 },
  { title: "París", artist: "Pinto Picasso", category: "sensual", year: 2017 },
  { title: "Aceptalo", artist: "Pinto Picasso ft. Sebas Garreta", category: "sensual", year: 2021 },
  { title: "Besos Mojados", artist: "Mayinbito", category: "sensual", year: 2021 },
  { title: "Creme de la creme", artist: "Mayinbito", category: "sensual", year: 2022 },
  { title: "Confía", artist: "Mayinbito ft. Jay Ramirez", category: "sensual", year: 2022 },
  { title: "Mil Pedazos", artist: "Mayinbito ft. Ralphy Dreamz", category: "sensual", year: 2022 },
  { title: "Entre Pasillos", artist: "Mayinbito ft. Sonce", category: "sensual", year: 2023 },
  { title: "Mientele", artist: "Mayinbito ft. Roman", category: "sensual", year: 2023 },
  { title: "Alma", artist: "Montelier ft. DJ Husky", category: "sensual", year: 2022 },
  { title: "El Amor de mi Vida", artist: "Montelier", category: "sensual", year: 2022 },
  { title: "Insomnio", artist: "Shama ft. DJ Husky", category: "sensual", year: 2022 },

  // 3. Remix (Pop, Reggaeton Remixes)
  { title: "Si Antes Te Hubiera Conocido", artist: "Karol G (Bachata Remix)", category: "remix", year: 2024 },
  { title: "Provenza", artist: "Karol G (Bachata Remix)", category: "remix", year: 2022 },
  { title: "MAMIII", artist: "Karol G (Bachata Remix)", category: "remix", year: 2022 },
  { title: "TQG", artist: "Karol G ft. Shakira (Remix)", category: "remix", year: 2023 },
  { title: "Hentai", artist: "Rosalía (Bachata Remix)", category: "remix", year: 2022 },
  { title: "Despechá", artist: "Rosalía (Bachata Remix)", category: "remix", year: 2022 },
  { title: "Monotonía", artist: "Shakira & Ozuna", category: "remix", year: 2022 },
  { title: "Crazy in Love", artist: "Beyoncé (Bachata Remix)", category: "remix", year: 2015 },
  { title: "Sobrio", artist: "Maluma (Bachata Remix)", category: "remix", year: 2021 },
  { title: "Cupido", artist: "Tini (Bachata Remix)", category: "remix", year: 2023 },
  { title: "Un Finde", artist: "FMK (Bachata Remix)", category: "remix", year: 2023 },
  { title: "Bebé", artist: "Camilo & El Alfa (Remix)", category: "remix", year: 2020 },
  { title: "Lala", artist: "Myke Towers (Bachata Remix)", category: "remix", year: 2023 },
  { title: "Vagabundo", artist: "Sebastian Yatra (Remix)", category: "remix", year: 2023 },
  { title: "Ella Baila Sola", artist: "Eslabon Armado (Remix)", category: "remix", year: 2023 },

  // 4. Emotional & Others (Artists, DJ Husky, SP Polanco)
  { title: "Palabritas", artist: "Daniel Santacruz", category: "others", year: 2014 },
  { title: "Salvame", artist: "Daniel Santacruz", category: "others", year: 2016 },
  { title: "Bachata Bolero", artist: "Grupo Extra", category: "others", year: 2018 },
  { title: "Si Fueras Mía", artist: "Grupo Extra", category: "others", year: 2020 },
  { title: "En Medio de la Noche", artist: "Chelion", category: "others", year: 2022 },
  { title: "Mi Vida", artist: "Chelion", category: "others", year: 2022 },
  { title: "Apretaito", artist: "Charles Luis", category: "others", year: 2022 },
  { title: "El Tonto", artist: "Charles Luis ft. DJ Nico", category: "others", year: 2023 },
  { title: "Dicelo", artist: "Román ft. Kira Brown", category: "others", year: 2022 },
  { title: "Mi Refe", artist: "Román ft. Blaraya", category: "others", year: 2023 },
  { title: "Caer", artist: "Sebas Garreta", category: "others", year: 2022 },
  { title: "With or Without You", artist: "Jhonny Sky (Bachata Ver.)", category: "others", year: 2015 },
  { title: "Por Que Te Niegas", artist: "Mickey Then ft. Jr", category: "others", year: 2019 },
  { title: "Bailame", artist: "DJ Husky", category: "others", year: 2021 },
  { title: "El Acuerdo", artist: "DJ Husky (Mashup)", category: "others", year: 2023 },
  { title: "Proceso", artist: "SP Polanco", category: "others", year: 2023 },
  { title: "Anónimos", artist: "SP Polanco", category: "others", year: 2023 },
  { title: "Escalofríos", artist: "SP Polanco", category: "others", year: 2023 },
  { title: "Masoquista", artist: "Performance Only", category: "others", year: 2023 },
  { title: "Un Movimiento", artist: "Performance Only", category: "others", year: 2023 },
  { title: "Khe", artist: "Many Rod & DJ Tronky", category: "others", year: 2024 },
  { title: "La Bachata", artist: "Manuel Turizo", category: "others", year: 2022 },
  { title: "TBT", artist: "Sebastian Yatra", category: "others", year: 2020 },
  { title: "Mas Bella", artist: "Jahil Lopez", category: "others", year: 2022 },
  { title: "Ta Ma Buena Que Tu", artist: "Unknown", category: "others", year: 2023 },
  { title: "Calumnia", artist: "Various Artists", category: "others", year: 2023 },
  { title: "Only You", artist: "Various Artists", category: "others", year: 2023 },
  { title: "La Estrategia", artist: "Various Artists", category: "others", year: 2017 }
];
